### PR TITLE
Project Apple Clone Completed - Feature branch Pull Request 

### PR DESCRIPTION
**Pull request by xtrmdarc**
This is the apple clone project I developed on my own. I kindly request a code review to be able to merge it into the master. I used FlexBox to completely align and position the elements in this project. These are the features I worked on:

-Added Navigation bar 
-Added the main section called hero section
-Added Featured section below the hero section.
-Added footer navigation.

### CODE REVIEW

**Comment by xtrmdarc** [comment]
Hi Reviewer, I had problems with Stickler validating my code. However, I run the Stylelint validation on my local environment and fixed all the issues.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @xtrmdarc. Great work. :+1: . Just a few changes are required to get this approved**
1. Include the apple logo on the leftmost section of navbar.
2. The four images below the main sections should be links. Enclose them in `<a>` tags.

**Optional:**
1. Change the `<section>` tags used in the main section to `<main>`
2. Change the color/font of text in the navbar to make it clearer.

**Also, I think you didn't turn on stickler for this repository, that is why there is no lint test result at all. Visit https://github.com/apps/stickler-ci and enable stickler for this repository**.

Make these changes and submit another code review request.

**Cheers :smile:**

**Status: Changes requested**

**Comment by xtrmdarc** [comment]
Hi @mosesogwo,
I believe that I already added the apple logo at the leftmost part of the navbar. I used background image as suggested in the curriculum to place the apple logo one of `<li>` elements of the navbar. Please kindly take a look at my screenshot below. 

Regarding Stickler, I did enable it and gave access to all my repositories. My safest bet is that this is a particular problem with this repository since I have successfully integrated it with past projects before. However, I can see It is enabled now without me having to do anything, it was probably a temporary glitch.

image

**Review by mosesogwo — APPROVED** [review]
**:trophy: Congratulations, your project is approved.**

For the Apple logo, you may want to download a copy of the image to your project folder and reference it from there. I haven't been able to load the image-url up till now.

You can now merge to master.

**Cheers:smile:**

**Status: Approved!**

**Pull request merged**
